### ISSUE TITLE
Running error when setting want_AB = False

### ISSUE THREAD

**Issue by SFeng978** [abacusorg/abacusutils#12]
I just got an error when running the prepare_sim.py with setting want_AB=False. 
Here is the error:

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/61905562/121507108-eb421580-ca16-11eb-80ec-e89de3accb9d.png">

It seems a problem with the variable 'deltac_rank' in this case.

**Comment by lgarrison** [comment]
@SandyYuan, can you take a look?

**Comment by SandyYuan** [comment]
This issue has been fixed in the newest version.
