### ISSUE TITLE
Fix periodicity in theory-box HOD code

### ISSUE THREAD

**Issue by lgarrison** [abacusorg/abacusutils#31]
From @boryanah in https://github.com/abacusorg/abacusutils/pull/28#discussion_r792818492, there appears to be at least one place where we use non-periodic KDTree where we should be using periodic KDTree. Let's fix that and double-check all the KDTree usage.

**Comment by boryanah** [comment]
Yep, will work on that -- KDTree should be non-periodic for the LCs and periodic for the box.

**Comment by boryanah** [comment]
merged into fix-origin branch
