### ISSUE TITLE
Some issues from NERSC

### ISSUE THREAD

**Issue by lgarrison** [abacusorg/abacusutils#9]
A few issues and suggestions from my tests of AbacusHOD at NERSC.  This was with v0.4.0, so possibly slightly out of date.

- [x] `Nthread_load` of 7 runs out of memory on Haswell nodes (128G).  4 works (maybe 5 or 6 would, too).  Should lower the default; most users will be at NERSC.
- [x] The recommended value of mem/20 in the docs may not be conservative enough
- [x] Maybe put `Nthread_load` in a different YAML section since it only applies to the prep stage? Like `prepare_sim: nthreads: 4`?
- [x] Maybe `nparallel` instead of `nthreads`, trying to emphasize that it's not just threads but also memory that will go up?
- [x] The distinction between `subsample_dir` and `scratch_dir` is not super clear. Maybe rename them to `prep_dir` and `output_dir`, or something like that? Or `prep_dir` could live under `prepare_sim: output_dir: '...', nthreads: ...`
- [ ] Is `prepare_sim` a clear enough name? Maybe `preprocess_sim` or `sim_staging`?
- [x] There's a lot of output that flies by when running these scripts, it's hard for an end user to tell if all is well. Maybe show a limited amount of progress information the user, and hide the rest behind a `--verbose` flag?
- [ ] Do we need a `config` directory if it's just going to hold one file?
- [ ] `prepare_sims.py config_file` would be more idiomatic than `prepare_sims.py --path2config config_file`, just because `config_file` is the primary argument. It can still be optional.
- [ ] Can remove the `>>>` in front of the scripts in the ReadTheDocs, it makes it hard to copy-paste. It's usually only needed to interleave code and output.

**Comment by SandyYuan** [comment]
I think the better name for prepare_sim is subsampling, but I would rather not change the name at this point. This name is showing up at a lot of places in the docs and the paper, and I think prepare_sim is fine. It is descriptive in a way too.

**Comment by SandyYuan** [comment]
re: config directory,
I like having a separate directory, because the user will likely have multiple configuration files.

**Comment by SandyYuan** [comment]
re: --path2config
I think it is fine.

**Comment by SandyYuan** [comment]
re: >>>
I updated the docs, but there is that weird part 

```
Within Python, you can run the same script with ::
from abacusnbody.hod import prepare_sim

prepare_sim.main(/path/to/config.yaml)
```

that isnt showing up right. I cant seem to fix it

**Comment by lgarrison** [comment]
On the prepare_sim name, "downsampling" might be an even better name than "subsampling", just because we already use the term "subsample" within Abacus to mean something slightly different.  I don't think it's too late to change the name, but if you would rather leave it, that's fine too.

On the docs, you just need a blank line after the `::`.  RST is touchy about spaces and newlines!

**Comment by lgarrison** [comment]
I think the last item I noticed from NERSC is that it's surprisingly easy to miss the whole two-stage workflow (prepare_sim before HOD) when skimming the docs.  This has already bitten one of our users!  I think if the "visual structure" of the Short Example documentation could be made to reflect the two-stage process, it would communicate the information more effectively.  This could be with sub-sections (e.g. "Step 1" and "Step 2"), and/or a numbered list of steps, and/or break-out blocks with `.. note::` or `.. warning::`.  There are a lot of options in RST.

**Comment by lgarrison** [comment]
I think all of these issues have been addressed in some form or another.
