### ISSUE TITLE
Trouble import abacusnbody

### ISSUE THREAD

**Issue by schwartzw** [abacusorg/abacusutils#90]
Hi there,

I am trying to import abacusnbody into jupyter-notebook but am having troubles. When I run the command: 

from abacusnbody.data.compaso_halo_catalog import CompaSOHaloCatalog" 

I get an error message saying:

No module named 'abacusnbody.version' 

In the error message I see it's trying to go to the abacusnbody directory where __int__.py is (which I 've checked I have) yet it won't install. I am very much not tech savvy, so this may be an easy fix. If so, I apologize for the waste of time but will still appreciate the help.

Best,
Weston

**Comment by lgarrison** [comment]
@schwartzw It sounds like you're able to import abacusnbody now; can I go ahead and close this issue?

**Comment by schwartzw** [comment]
Yes you can. Sorry, I forgot to come back to let you know it started working
