### ISSUE TITLE
Parallel_Numpy_Rng not found

### ISSUE THREAD

**Issue by schwartzw** [abacusorg/abacusutils#93]
Hello,

I am trying to use AbacusHOD but keep running into problems. I am following the examples provided here: 

https://abacusutils.readthedocs.io/en/latest/hod.html

but when I run the command: 

from abacusutils.abacusnbody.hod.abacus_hod import AbacusHOD

it tells me there is no module named 'parallel_numpy_rng'. I've tried looking online for resources regarding this package but haven't been able to find any. Where is this module originally from (i.e. where is it getting called from) and what may be some ways to fix this issue? I understand what I am writing is pretty vague, so I will be happy to elaborate further if necessary

Best,
Weston

**Comment by lgarrison** [comment]
Hi there, it sounds like you might have cloned but not installed `abacusutils`. If you've cloned the repo so you can work on the source code, please follow these instructions to install `abacusutils` as an editable package: https://abacusutils.readthedocs.io/en/latest/installation.html#installing-from-cloned-repository

If you don't need to work on the source code, then you should be able to just `pip install abacusutils`, which will not use the cloned repo.

Also, the import commands should always use `abacusnbody`, not `abacusutils`.

**Comment by schwartzw** [comment]
I guess I didn't install it correctly the first time, but after uninstalling and re-installing it seems to work just fine now. Thank you for taking the time to help me!

**Comment by lgarrison** [comment]
Great! Glad it's working. I'll go ahead and close this; please feel free to file another issue if something else doesn't work.
