### ISSUE TITLE
Sample AbacusHOD: index out of range

### ISSUE THREAD

**Issue by schwartzw** [abacusorg/abacusutils#95]
Hello again,

I am still working on getting AbacusHOD to work and I am stuck on the example where we construct an AbacusHOD object. When I run the provided cell, I get an error when the code tries to run the 'newBall' line. When I run this, the error message it gives me is: 

~/.local/lib/python3.6/site-packages/abacusnbody/hod/abacus_hod.py in staging(self)
    351             halo_info_fns = \
    352                             list((sim_dir / simname / 'halos' / ('z%4.3f'%self.z_mock) / 'halo_info').glob('*.asdf'))
--> 353         f = asdf.open(halo_info_fns[0], lazy_load=True, copy_arrays=False)
    354         header = f['header']
    355 

IndexError: list index out of range

I opened abacus_hod.py to check the variables being called and that led me to abacus.yaml. Currently the path to my asdf files is:

AbacusSummit_base_c000_ph000/halos/z0.000/halo_info

And the beginning of my abacus_hod.yaml file looks like: 

# Simulation parameters
sim_params:
    sim_name: 'AbacusSummit_base_c000_ph000'                                  
    sim_dir: 'AbacusSummit_base_c000_ph000/halos/z0.100/halo_info/'
    output_dir: 'AbacusSummit_base_c000_ph000/mock_summit/'
    subsample_dir: 'AbacusSummit_base_c000_ph000/cleaned_summit/'
    z_mock: 0.1                                                             
    cleaned_halos: True

I've tried other variations of this but I still get the same error message. At this point I am unsure whether the error is due to defining these variables incorrectly or if it's due to something different. As always, please let me know what further information you need in order to help

Thank you in advance,
Weston

**Comment by lgarrison** [comment]
Did you manage to fix this? Sorry I haven't had a chance to take a look; there might be a few things happening. The first might be that `sim_dir` needs to be the directory that contains the simulations; the second might be that one of the paths you wrote has `z0.000`, which is probably wrong since AbacusSummit only goes to z=0.1; the third might be that you're running an old version of Python (3.6), and so you may be stuck on an old version of abacusutils as a result.

**Comment by schwartzw** [comment]
No apologies needed; I was able to get this issue resolved by explicitly defining halo_info_fns in my abacus_hod.py file. That may have caused a new issue though. Now when I run the cell it tells me it is unable to open the file: 

'abacusnbody/cleaned_summit/AbacusSummit_base_c000_ph000/z0.100/halos_xcom_0_seed600_abacushod_oldfenv_new.h5'

I don't have this file and the path it references doesn't exist, but from my understanding AbacusHOD is supposed to construct the path and the file (?)

I don't believe this issue is caused by how I defined halo_info_fns as the parts of the code that are flagged don't reference halo_info_fns or the sim_param variables that define it. I believe these types of files are supposed to be the files that are generated by AbacusHOD that contain the mock data, but I could be mistaken

**Comment by lgarrison** [comment]
@SandyYuan will know for sure, but I think this file is supposed to be generated by the `prepare_sim` part of the code (https://abacusutils.readthedocs.io/en/latest/hod.html#short-example). Were you able to run that successfully?

Also, you shouldn't have to modify `abacus_hod.py` to get the code to find the halo_info files. If the directories in the YAML file aren't set correctly, that could cause problems down the line (even if it's not causing this problem).

**Comment by schwartzw** [comment]
I was able to follow the example (including successfully running prepare_sim.main) all the way up until having to use AbacusHOD. I removed the modification made to 'abacus_hod.py' and tried focusing on setting the YAML file up correctly but to no avail. I've followed the example YAML file in the test directory so I believe my YAML is correctly set up. With my asdf files being in the absolute path of '/abacusutils/abacusnbody/AbacusSummit_base_c000_ph000/halos/z0.100/halo_info/' my YAML file now looks like this: 

sim_params:
sim_name: 'AbacusSummit_base_c000_ph000'
sim_dir: './abacusutils/abacusnbody/'
output_dir: './abacusutils/abacusnbody/mock_summit/'
subsample_dir: './abacusutils/abacusnbody/cleaned_summit/'
z_mock: 0.1
cleaned_halos: True

Looking at the abacus_hod.py code, it looks like halo_info_fns is defined as:
 list((sim_dir / sim_name / 'halos' / ('z%4.3f'%self.z_mock) / 'halo_info).glob('*.asdf')). 

So I think given my sim_params, halo_info_fns is construced to be a list of i paths of the form: ./abacusutils/abacusnbody/AbacusSummit_base_c000_ph000/halos/z0.100/halo_info/file[i].asdf 

Is this the correct interpretation? If so, are there any other dependancy files that I should edit to match my personal environment?

**Comment by lgarrison** [comment]
Try putting the simulations in a directory like `/home/schwartzw/data/AbacusSummit/`. This directory should contain directories like `AbacusSummit_base_c000_ph000` (and any other sims). Then, you would configure your YAML like:
```yaml
sim_params:
    sim_name: 'AbacusSummit_base_c000_ph000'                                 # which simulation
    sim_dir: '/home/schwartzw/data/AbacusSummit/'
    output_dir: '/home/schwartzw/data/abacushod_mocks/'          # where to output galaxy mocks
    subsample_dir: '/home/schwartzw/data/abacushod_staging/'                 # where to output subsample data
```

Note how all those directories begin with `/` (absolute), not `./` (relative). The YAML file in the test directory uses relative paths because it needs to be able to run on any system, but it will definitely be easiest for you to get this working with absolute paths.

> With my asdf files being in the absolute path of '/abacusutils/abacusnbody/AbacusSummit_base_c000_ph000/halos/z0.100/halo_info/' 

Your data probably isn't in `/abacusutils/abacusnbody/...`, because that would mean you have an `abacusutils` directory in your filesystem root, which requires root privileges to write to and would definitely not be a good idea! It's probably in `/home/schwartzw/abacusutils/abacusnbody/...` or something like that.


Speaking of which, it sounds like your data files are in a source code directory. It's good practice to keep code and data separate, hence my suggestion to make a `/home/schwartzw/data/AbacusSummit/` directory and put the sims there.

**Comment by schwartzw** [comment]
I edited my YAML file to match that and I think that's getting us closer to this working. After moving my data to a different directory and editing the YAML file, when I run the command: ```prepare_sim.main('abacusutils/scripts/hod/config/abacus_hod.yaml')``` it first prints messages saying:

``` python
compiling compaso halo catalogs into subsampled catalogs
processing slab processing slab 01
loading sub halo catalog

loading sub halo catalog
```

which wasn't previously displayed (which is why I think we're getting closer to a solution). It then also prints an error at the very end stating: 

```python
FileNotFoundError: Cleaning info not found. File path was: "/lhome/schwartzw2024/linux/schwartzw/data/AbacusSummit/cleaning/AbacusSummit_base_c000_ph000/z0.100/cleaned_halo_info/cleaned_halo_info_001.asdf". To load the uncleaned catalog, use `cleaned=False`.
```

It was my understanding, ```prepare_sim.main``` is supposed to create the cleaned halo files and the path, but looking back over https://abacussummit.readthedocs.io/en/latest/data-access.html it seems I may need to download them. I've gone over the data access procedures and I am wondering if there is a way to download only specific cleaned halo files. Currently I only see the option to download the entire set which I don't have space for (~99 GB)

**Comment by lgarrison** [comment]
Cleaning is actually separate from the HOD code. When you download the
simulation data, it should already come with a directory called "cleaning"
that contains the catalog cleaning info. If you put that directory at the
path printed out in the error message, it should work.

**Comment by schwartzw** [comment]
I feel so silly for not realizing that. I downloaded them and placed them in the proper locations and that got rid of ```FileNotFoundError```. Now when I run ```prepare_sim.main(/../../)``` I get ```AssertionError```.  I think it is due to line 791 in the ```compaso_halo_catalog.py``` file but I am not entirely certain. Line 791 is: 
``` 
N_halo_per_file = np.array([len(af[self.data_key][list(af[self.data_key].keys())[0]]) for af in afs])
for _N,caf in zip(N_halo_per_file,cleaned_afs):
     assert len(caf[self.data_key][next(iter(caf[self.data_key]))]) == _N  # check cleaned/regular file consistency
```

I can't find what _N is supposed to be; I've searched through ```prepare_sim.py``` and ```compaso_halo_catalog.py``` but found nothing

**Comment by lgarrison** [comment]
Is there any chance that you downloaded the wrong cleaning files? I.e. that they are for a different simulation or a different redshift? That is pretty much the only way that assertion can be triggered. You can always inspect the ASDF file headers directly with a command line too like `less` to see which simulation and redshift they come from.

**Comment by schwartzw** [comment]
After reviewing the files and paths, I have finally been able to get this working. Thank you so much for all of the time and help, I greatly appreciate it!

**Comment by lgarrison** [comment]
Great, glad it's working!
